function dy = HClODE(t, y, kp, km, b)
    % Transform to complete list of substances
    % y contains H2, Cl2 and HCl only
    c = [y(1), b(1) - 2 * y(1) - y(3), y(2), b(2) - 2 * y(2) - y(3), y(3)];
    %    H2    H                       Cl2    Cl                     HCl
%     disp([t, c]);
    dy = [-kp(1) * c(1) + km(1) * c(2) ^ 2 ...
            - kp(4) * c(1) * c(4) + km(4) * c(2) * c(5);...
          -kp(2) * c(3) + km(2) * c(4) ^ 2 ...
            - kp(3) * c(2) * c(3) + km(3) * c(4) * c(5);...
          kp(4) * c(1) * c(4) - km(4) * c(2) * c(5) ...
            + kp(3) * c(2) * c(3) - km(3) * c(4) * c(5)];
end